### PR TITLE
Link "Bitcoin" in FAQ to We Use Coins video

### PR DESCRIPTION
**Pull request by sunnankar**
No change of text. Added URLs to WeUseCoins.com for the What is Bitcoin video and What is Bitcoin Mining video.

### CODE REVIEW

**Comment by saivann** [comment]
Bitcoin.org already links to WeUseCoins (which was acquired by @sunnankar to my undestanding) quite a few times on the website. I'm not sure about the benefit of adding more links?

**Comment by saivann** [comment]
@sunnankar BTW the previous owners of the website never released the video source under an open-source license. Any chance this might happen now?

**Comment by sunnankar** [comment]
The FAQ section could use more citations that go into depth on the issues. I am trying to add a few from a variety of resources.

OT: Is there anyway you could transfer over the WUC/WUC repo so confusion can be mitigated? With it being fairly abandoned and neglected for 18 months I want to start getting it into better order.

I got about 8+ additional subtitle files added and uploaded to Youtube so we may have a few to update here. Also, on the Readme I have linked collated the state of various translations. A friend also did a Croatian translation (to keep in mind in case you add that here).

As for any of the licenses, etc. I have not really looked into any of that yet. I suppose I can add it to my long to-do list since there might be legal implications to changing the license and it would be good to know what all of the ramifications would be before changing anything.

Thanks.

**Comment by saivann** [comment]
@sunnankar Unfortunately I don't have any access to the previous WUC repository anymore. Regarding the license, actually you appear to have MIT licensed the website (https://github.com/sunnankar/wuc-new/blob/gh-pages/LICENSE). If you do the same with the video (and release the video and audio sources), people will be able to make full voice translations.

**Comment by harding** [comment]
Closing: adding more links to WeUseCoins doesn't seem advantageous, and there has been no discussion on this PR in over a week.  We can reopen at any time if discussion resumes.

**Pull request closed without merging**
