### PR TITLE
Full Node Guide: Add Windows 8.x Instructions

### PR DESCRIPTION
**Pull request by harding**
Preview: http://dg1.dtrt.org/en/full-node#windows-8x

Courtesy of @veqtrus, with assistance from @gurnec and some quick Q&A with @laanwj, this PR adds instructions to the full node guide for running Bitcoin Core on Windows 8 and 8.1. It has three commits:

1. A tiny typo fix.

2. Variablize some text in the existing Windows 7 section so it can be consistent between Win 7/8.

3. The new Windows 8.x instructions.

Note, I took @gurnec's advice in issue #825 and didn't add instructions messing around with the file permissions on `bitcoin.conf` in Windows.

As mentioned before, I know very little about modern Windows, so I'd heartily appreciate a through proofreading of the section by someone familar with the platform.

### CODE REVIEW

**Comment by veqtrus** [comment]
> After downloading the file to your desktop or your Downloads folder
> (`C:\Users\YOUR_USERNAME\Downloads`), run it by double-clicking
> its icon. Windows will ask you to confirm that you want to run it:

You may want to change `C:\Users\YOUR_USERNAME\Downloads` to `C:\Users\<YOUR USER NAME>\Downloads` for consistency.

**Comment by harding** [comment]
@veqtrus good catch, thanks!  I fixed it.  Did you see any other potential problems?

**Comment by veqtrus** [comment]
This is a cosmetic detail but when not right-clicking the Command Prompt icon on the start screen (e.g. when not running it as an administrator) it looks like [this](http://i.imgur.com/MNYuy6q.png).

**Comment by harding** [comment]
@veqtrus to clarify, I should use a cut-out of that image you provided to replace this image?  http://dg1.dtrt.org/img/full-node/en-win8-running-cmd.png

**Comment by veqtrus** [comment]
@harding yes, no need to run as administrator.

**Comment by harding** [comment]
@veqtrus updated, thanks!  Anything else I can improve?

**Comment by harding** [comment]
More feedback is always welcome, but in the absence of any major critical feedack, I will merge this around 14:00 UTC Tuesday.

**Pull request merged**
