### PR TITLE
Mailing list move

### PR DESCRIPTION
**Pull request by laanwj**
Move the mailing list from sourceforge to Linux Foundation.

Note: this does not update the text of all translations, which in many cases still refers to sourceforge, just the link and link text.

### CODE REVIEW

**Comment by btcdrak** [comment]
ACK

**Comment by saivann** [comment]
I have added a commit to stop mentioning sourceforge in the English texts (so translations can later be updated).

@laanwj Do you know what we should do with bitcoin-security@lists.sourceforge.net?

**Comment by harding** [comment]
@saivann bitcoin-security@SF is staying there for the time being.

**Comment by harding** [comment]
Reviewed diff and the previews in English and Spanish, and also looked for any other relevant strings.  LGTM.  I'm going to merge now, thanks!

**Comment by syaifudin857** [comment]
Join

**Pull request merged**
