### PR TITLE
Links: Replace Dead BitLegal.io With Wikipedia

### PR DESCRIPTION
**Pull request by harding**
BitLegal.io is no longer available, with whois saying the domain is being deleted and [this Reddit post](http://www.reddit.com/r/Bitcoin/comments/2t9oyg/anyone_know_what_happened_to_bitlegalio_website/) claiming the site maintainer no longer has time for it. As suggested by Reddit user /u/SatoshisGhost (thanks!), this replaces the links to bitlegal with links to a Wikipedia article:

    s^http://bitlegal.io/^https://en.wikipedia.org/wiki/Legality_of_bitcoin_by_country^

(Plus manual updating of two additional links in the Slovakian translation which referenced a Slovakia-specific page on the BitLegal.io site.)

If a better resource appears, we can link to that instead.

### CODE REVIEW

**Comment by saivann** [comment]
LGTM, thanks!

**Comment by harding** [comment]
@saivann thanks!

In the absence of critical feedback, this will be merged around 20:00 UTC Tuesday.

**Comment by luke-jr** [comment]
Disagree with using Wikipedia as a reference for anything, but ACK if nothing better exists.

**Comment by harding** [comment]
@luke-jr I will definitely be keeping my eye out for a better resource.  I really liked BitLegal.io.

**Pull request merged**
