### PR TITLE
Rename HW.1 to Ledger Nano

### PR DESCRIPTION
**Pull request by EricLarch**
The hardware wallet HW.1 is now known as "Ledger Nano". The link from the actual version of bitcoin.org is ledgerwallet.com but name and screenshot are HW.1.

This pull request is updating names and screenshort, so everything is up to date and correct.

References issue #696

### CODE REVIEW

**Comment by harding** [comment]
@EricLarch @btchip thanks!  This looks good to me, so (if nobody else sees any problems) I'll merge it tomorrow.

Todo list for myself:

* [ ] Squash
* [ ] Close #696 from commit
* [ ] Make sure new image is optimized

**Comment by harding** [comment]
Note: I haven't merged this because, last I heard, @crwatkins is waiting for a reply from @EricLarch about some possibly-significant differences between the HW.1 and the Ledger Nano.

**Comment by EricLarch** [comment]
Me and @btchip have replied to the questions a few days ago. From my understanding everything was fine from our answers. 
I'm available for any additional information on the subject.

**Comment by harding** [comment]
It looks like all of the questions have been answered---thanks everyone!  I'll merge this within the next hour.

**Pull request closed without merging**
