### PR TITLE
Add NBitcoin to the list of free software projects

### PR DESCRIPTION
**Pull request by NicolasDorier**

### CODE REVIEW

**Comment by harding** [comment]
NBitcoin looks legit to me, and it has commits from community members I recognize.  @NicolasDorier can you amend your commit to put NBitcoin on the list in alphabetical order (between Multibit and Obelisk)?

**Comment by NicolasDorier** [comment]
Thanks, fixed and rebased.

**Comment by harding** [comment]
LGTM.  Thanks!

In the absence of critical feedback, I'll merge this around 01:00 UTC Friday.

**Comment by saivann** [comment]
LGTM, sorry that I haven't commented in the last months!

**Pull request merged**
