### PR TITLE
Add links to givebtc.org

### PR DESCRIPTION
**Pull request by saivann**
As suggested in #734

In the absence of critical feedback, this pull request will be merged on February 8th.

### CODE REVIEW

**Comment by harding** [comment]
LGTM.  Thanks!

**Comment by luke-jr** [comment]
Page 23 misexplains Bitcoin in an attempt to go into unreasonably technical details and encourages address reuse. It's not clear how to get this resolved. While it may arguably not be a direct security risk (worst case scenario, losing all the funds, it's the same as if nobody donated in the first place), not even explaining the risks being taken on may lead it to be used outside of the charity context.

**Comment by saivann** [comment]
@luke-jr By "unreasonably technical details" I guess you are referring to mentioning "private keys"? Maybe you could make some suggestions in case they plan on updating the document? I guess it'll be quite hard to discourage address reuse for the specific case of printed materials and websites, but indeed, maybe they can consider the idea of adding more details on the lack of privacy, and why reusing addresses in other scenarios may not be very suitable.

@FrancisPouliot Please see @luke-jr comment above in case you want to comment.

**Comment by luke-jr** [comment]
Yeah, end users should never be exposed to private keys, and should see the wallet as an opaque entity/file itself. It makes false equivalences between bitcoin addresses and email addresses, as another example. Probably those paragraphs should be rewritten from the perspective of "you can generate an address - this is used to receive a single transaction generally, but when you don't care who is sending it, you can often get away with just publishing it for everyone to use (although this is still a bad idea for security and privacy concerns)"

**Comment by harding** [comment]
@luke-jr do you consider this a blocking issue, or is it ok to merge this commit?

**Comment by FrancisPouliot** [comment]
@luke-jr can't really have it both ways, i.e. say it's too technical and then say that I don't explain address re-use. Later in the document there is a specific section about wallets written by Michael Perklin on the topic. 

I don't make false equivalences between an email address and a Bitcoin address - it's just a very basic security tip, i.e. keep your private key safe, with an everyday example: "You can think of them as your email address and your email password: you share your email address with others to receive mail and you use your password to view or send email."

This document will never be perfect to satisfy everyone - I had to make editorial choices as to how I would explain some things considering the target audience.The topic of addres re-use is covered later in the doc (see p. 29) and the nature of a Bitcoin address is covered before (p.10 and 11)

**Comment by harding** [comment]
Thanks @FrancisPouliot for your clarification!

I'm guessing that @luke-jr doesn't think the page 23 problem is a blocking issue, so---unless I hear otherwise from him---I plan to merge this commit in 24 hours (around 15:00 UTC Wednesday).

**Pull request merged**
