### PR TITLE
Updates for v0.10

### PR DESCRIPTION
**Pull request by saivann**
Live preview: http://dg4.dtrt.org/en/download

Diff of formatting-only changes to the release notes: http://dg4.dtrt.org/diff.html
(diff will not be part of actual site)

* [x] Release notes may need to be updated if they have changed after Bitcoin Core commit https://github.com/bitcoin/bitcoin/commit/327d3e8824e1e2d31cbc8281a042429c99baaf5c (Feburary 9th)

* [ ] `_releases/2015-02-16-v0.10.0.md` needs to be renamed with the right UTC date on the day of the release.

* [ ] (Optional) A .torrent file should be automatically created in the bin/0.10.0 directory once the binaries are uploaded.  Convert that .torrent link into a magnet link using a tool like `transmission-show -m "bitcoin-0.10.0.torrent"` and add that magnet URI needs to the YAML header of the file above: `magnetlink: ...`  (a commented-out example is provided).  This is optional because it can be done after this is merged (@harding is planning on doing it).

* [ ] Check the links.  Especially check the link for the Mac OSX .dmg, as that frequently changes.  If any links are broken, edit the file `_templates/download.html` (the OSX link is currently set to the same as used in RC4, with a commented-out example on line 12 of the download template providing the common alternative link)

Feel free to PM `harding` on Freenode to make the above changes when the release is near.

This pull request makes required changes to the download page for v0.10.0 and all texts refering to the long synchronization time. It should be merged when v0.10.0 is released.

Changes in this pull request:

* Set filenames once in the download page
* Edit download page for new or updated files
* Add link to the source code, GitHub and torrent download
* Edit: Replace long sync instructions by short instructions to run a full node on the download page

### CODE REVIEW

**Comment by harding** [comment]
@saivann I'm going to update this branch today with the latest release notes.  I just wanted to let you know since you usually force-push your updates. :-)

**Comment by harding** [comment]
The ready-to-merge release notes have been updated those included in RC4 and I've updated @saivann's description of the PR with new preview links and a slightly expanded merge checklist.  I'll keep that post updated with the latest information about this PR.

**Comment by harding** [comment]
@laanwj I've just updated this and it should be ready to merge.  I've placed a checklist in @saivann's original description of this PR (the top post).

The only thing I'm worried about is the OSX .dmg link---the file name used in RC4 (`bitcoin-0.10.0*.dmg`) was not the one Saïvann expected (bitcoin-0.10.0-osx.dmg`).  I've set the name in this PR to use the format from RC4, but I also added a commented-out variable in the file restoring the link back to the one Saïvann expected.  Instructions are in the checklist

I'm heading to bed now, but I wrote an every-minute shell loop to sound an alarm when you upload the binaries, so hopefully I should be available to fixup this commit if necessary.

**Comment by harding** [comment]
@laanwj I see the uploads have been made.  Updating and testing this now, and I'll merge once that's done.

**Comment by laanwj** [comment]
Yep, good catch :) uploaded 0.10 final + signed SHA256SUMS.asc are in place.

**Comment by saivann** [comment]
Note: I just updated the automatic torrent; all public trackers used appeared down so I added two others...

**Comment by harding** [comment]
@saivann cool.  I'll redownload and update the magnet link if it changes.

**Comment by harding** [comment]
Merged.  I also verified the .asc, checked it against some of the download from the site (I'll do the rest now) and against the all the files in the .torrent.  Thanks!

**Comment by saivann** [comment]
Site has updated, looks all good! The .dmg link works. I also confirm that signatures, torrent and magnet link are correct.

Thanks @harding and @laanwj, this is an historical release.

**Comment by schildbach** [comment]
Just an hour old, and it's already historical (-:

Thanks everyone!

**Comment by laanwj** [comment]
Confirmed it works. Thank a lot @saivann and @harding!

**Pull request closed without merging**
