### PR TITLE
Wallets: Re-Add Circle.com To The Wallet Page

### PR DESCRIPTION
**Pull request by harding**
Opened at the request of @ywecur in pull #700, this pull request re-adds Circle.com to the wallets page with the same content it had previously.

Circle was removed because it did not implement HSTS, but it does now:

    $ curl -s -D- https://circle.com/ | grep Strict
    Strict-Transport-Security: max-age=15552000

### CODE REVIEW

**Comment by saivann** [comment]
LGTM. In the absence of critical feedback, this pull request will be merged on February 6th.

**Comment by ywecur** [comment]
Thank you @harding , I much appreciate your help!

**Comment by luke-jr** [comment]
I thought Circle didn't want to be on bitcoin.org? Are they okay with this?

**Comment by harding** [comment]
@luke-jr according to @saivann in [this comment](https://github.com/bitcoin/bitcoin.org/pull/700#issuecomment-72302735):

> OK some quick update; apparently if some people really want to add Circle, the contacts I've talked to don't seem to have any serious issue either way.

**Pull request merged**
