### PR TITLE
Logo SVG optimisation

### PR DESCRIPTION
**Pull request by louisjc**
I opened the svg file of the logo and I think it deserves some optimizations : I removed useless groups, ids and tags. The result looks identical but the new file is two time smaller.

Also the xml refers to the Creative Commons license while the file is under MIT.

### CODE REVIEW

**Comment by saivann** [comment]
@louisjc Is there a way to optimize these SVG automatically? I guess most if not all SVG on bitcoin.org would deserve such optimizations... Thanks for opening this pull request!

**Comment by harding** [comment]
@saivann for the record, I tried using [scour](http://www.codedread.com/scour/) a few months ago on some of our dev docs SVGs, but the results weren't consistently good like the optipng results.

**Comment by louisjc** [comment]
@saivann The goal is to group transformations together, remove inkscapes tags and ids (both unnecessary here),   while keeping numbers untouched to not affect the quality. I know this [javascript tool](http://petercollingridge.appspot.com/svg-editor) does it (it does not affect quality but some optimization need to be done by hand) maybe the [Python version](https://github.com/petercollingridge/SVG-Optimiser) (never used this one) could do the whole folder at a time. 

I'm going to check it later.

**Comment by saivann** [comment]
@harding @louisjc Thanks!

This pull request renders fine on all browsers I have tested. In the absence of critical feedback, this pull request will be merged on February 2th.

**Comment by harding** [comment]
@louisjc the 0.10 branch shouldn't be merged into this commit, as Bitcoin Core 0.10 hasn't been released yet.  Can you please rebase-remove that merge?  (If you don't know how, let me know and I'll provide instructions.)  Thanks.

**Comment by louisjc** [comment]
@harding Fixed, it was unintentional.

**Comment by saivann** [comment]
@louisjc @harding Merged, thanks!

**Pull request merged**
