### PR TITLE
Small change: make Getting started more dense

### PR DESCRIPTION
**Pull request by louisjc**
Just a very small change, I've reduced the margin on the Getting started page. This make the page a bit denser, useful for mobile and small screens.

### CODE REVIEW

**Comment by saivann** [comment]
@louisjc Can you apply this to the mobile layout only perhaps, to keep the desktop layout aerated? At the end of the CSS file you can file the rules applied to the mobile layout.

**Comment by louisjc** [comment]
Don't you think this is an improvement for both mobile and desktops? My window size did make a perfect argument for it :

margin

**Comment by saivann** [comment]
@louisjc Mmh, to be honest I think the existing margins are better on desktop, insofar as keeping things areated seems to be the usual watchword for modern designs. However my main issue is with the lack of margin between the "How to use Bitcoin" and "How to accept Bitcoin" subsections of the page.

**Comment by louisjc** [comment]
Didn't saw you want to keep it aerated (I read unaltered), i think this is a good point you're right! I think I should close it then.

While I'm in the small layout changes, is there a reason why none of the images are center (I think about [this page](https://bitcoin.org/en/how-it-works) and the [faq](https://bitcoin.org/en/faq)), I was going to open a pull about it but I would like to hear your opinion before.

**Comment by harding** [comment]
@louisjc I like the idea of centering images.  I've wanted that before for the dev docs.

I don't want to impose, but if you're looking for a project, another thing I'd like to see done is have all of the clickable links on the site use the same blue color (including the small boxes like Read More on the getting started page), and then make sure we don't use a similar blue color for anything else (like subheads).

I'm no UI expert, but I think having a single color for all links is recommended.

**Comment by saivann** [comment]
@louisjc Personally I think your changes are an improvement for the mobile layout! In case you want to apply it only to mobiles :) . Thanks for your work on this. Centering pictures is generally fine with me!

**Comment by louisjc** [comment]
@saivann Sorry for the delay, I've moved the change to the mobile section :)

**Comment by harding** [comment]
@louisjc looks good to me, thanks!  I'll merge this in the next time I do a merge.

**Pull request merged**
